FROM node:16 as development

WORKDIR /app

COPY . .

RUN rm -rf node_modules
RUN rm -rf dist
RUN rm -rf pnpm-lock.yaml

RUN npm install -g  typescript tsc-watch

RUN npm install

EXPOSE 4000

CMD ["npm", "run", "dev"]
